#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
profile="${1:-local}"
output_mode="${2:-write}"

case "$profile" in
  local)
    application_id="com.avalsys.avradio.dev"
    ;;
  production)
    application_id="com.avalsys.avradio"
    ;;
  *)
    echo "Unsupported profile: $profile" >&2
    exit 1
    ;;
esac

eval "$("$repo_root/scripts/resolve-infisical-bootstrap-env.sh" "$profile")"

varlock_bin="$repo_root/node_modules/.bin/varlock"

if [ ! -x "$varlock_bin" ]; then
  echo "varlock CLI is required. Run 'bun install' in $repo_root." >&2
  exit 1
fi

printenv_value() {
  local key="$1"
  "$varlock_bin" printenv --path "$repo_root/" "$key"
}

properties_escape() {
  printf '%s' "$1" | sed \
    -e 's/\\/\\\\/g' \
    -e 's/=/\\=/g' \
    -e 's/:/\\:/g'
}

preserve_local_property() {
  local key="$1"
  local file="$2"

  if [ ! -f "$file" ]; then
    return 0
  fi

  sed -n "s/^${key}=//p" "$file" | head -n 1
}

clerk_publishable_key="$(printenv_value CLERK_PUBLISHABLE_KEY)"
premium_product_ids="$(printenv_value AVRADIO_PREMIUM_PRODUCT_IDS)"
support_email="$(printenv_value AVRADIO_SUPPORT_EMAIL)"
avapps_api_base_url="$(printenv_value AVRADIO_AVAPPS_API_BASE_URL)"
account_management_url="$(printenv_value AVRADIO_ACCOUNT_MANAGEMENT_URL)"
terms_url="$(printenv_value AVRADIO_TERMS_URL)"
privacy_url="$(printenv_value AVRADIO_PRIVACY_URL)"
auth_provider="$(printenv_value AVRADIO_AUTH_PROVIDER)"
auth_web_url="$(printenv_value AVRADIO_AUTH_WEB_URL)"
auth_callback_scheme="$(printenv_value AVRADIO_AUTH_CALLBACK_SCHEME)"
auth_callback_host="$(printenv_value AVRADIO_AUTH_CALLBACK_HOST)"

required_values=(
  clerk_publishable_key
  premium_product_ids
  support_email
  account_management_url
  terms_url
  privacy_url
)

for value_name in "${required_values[@]}"; do
  if [ -z "${!value_name:-}" ]; then
    echo "Missing required value: $value_name" >&2
    exit 1
  fi
done

rendered_config="$(cat <<EOF
## Generated by scripts/generate-android-local-properties.sh for profile '$profile'
AVRADIO_APPLICATION_ID=$(properties_escape "$application_id")
AVRADIO_AUTH_PROVIDER=$(properties_escape "$auth_provider")
CLERK_PUBLISHABLE_KEY=$(properties_escape "$clerk_publishable_key")
AVRADIO_AVAPPS_API_BASE_URL=$(properties_escape "$avapps_api_base_url")
AVRADIO_AUTH_WEB_URL=$(properties_escape "$auth_web_url")
AVRADIO_AUTH_CALLBACK_SCHEME=$(properties_escape "$auth_callback_scheme")
AVRADIO_AUTH_CALLBACK_HOST=$(properties_escape "$auth_callback_host")
AVRADIO_PREMIUM_PRODUCT_IDS=$(properties_escape "$premium_product_ids")
AVRADIO_SUPPORT_EMAIL=$(properties_escape "$support_email")
AVRADIO_ACCOUNT_MANAGEMENT_URL=$(properties_escape "$account_management_url")
AVRADIO_TERMS_URL=$(properties_escape "$terms_url")
AVRADIO_PRIVACY_URL=$(properties_escape "$privacy_url")
EOF
)"

target_file="$repo_root/apps/android/local.properties"
sdk_dir="$(preserve_local_property sdk.dir "$target_file")"
ndk_dir="$(preserve_local_property ndk.dir "$target_file")"
cmake_dir="$(preserve_local_property cmake.dir "$target_file")"

if [ -n "$sdk_dir" ]; then
  rendered_config="${rendered_config}
sdk.dir=${sdk_dir}"
fi

if [ -n "$ndk_dir" ]; then
  rendered_config="${rendered_config}
ndk.dir=${ndk_dir}"
fi

if [ -n "$cmake_dir" ]; then
  rendered_config="${rendered_config}
cmake.dir=${cmake_dir}"
fi

case "$output_mode" in
  write)
    umask 077
    printf '%s\n' "$rendered_config" > "$target_file"
    echo "Wrote $target_file for profile '$profile'."
    ;;
  stdout)
    printf '%s\n' "$rendered_config"
    ;;
  *)
    echo "Unsupported output mode: $output_mode" >&2
    exit 1
    ;;
esac
