#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
profile="${1:-local}"
output_mode="${2:-write}"

case "$profile" in
  local)
    application_id="com.avalsys.avradio.dev"
    ;;
  production)
    application_id="com.avalsys.avradio"
    ;;
  *)
    echo "Unsupported profile: $profile" >&2
    exit 1
    ;;
esac

if ! command -v infisical >/dev/null 2>&1; then
  echo "infisical CLI is required but was not found in PATH." >&2
  exit 1
fi

eval "$("$repo_root/scripts/resolve-infisical-bootstrap-env.sh" "$profile")"

domain="${INFISICAL_SITE_URL:-https://app.infisical.com}"
api_domain="$domain"
if [[ "$api_domain" != */api ]]; then
  api_domain="${api_domain%/}/api"
fi

token="$(
  infisical login \
    --method universal-auth \
    --client-id "$INFISICAL_CLIENT_ID" \
    --client-secret "$INFISICAL_CLIENT_SECRET" \
    --domain "$api_domain" \
    --plain \
    --silent
)"

secret_payload="$(
  infisical export \
    --token "$token" \
    --domain "$api_domain" \
    --env "$INFISICAL_ENVIRONMENT" \
    --projectId "$INFISICAL_PROJECT_ID" \
    --format dotenv \
    --silent
)"

dotenv_value() {
  local key="$1"
  printf '%s\n' "$secret_payload" | sed -n "s/^${key}='\\(.*\\)'$/\\1/p" | head -n 1
}

properties_escape() {
  printf '%s' "$1" | sed \
    -e 's/\\/\\\\/g' \
    -e 's/=/\\=/g' \
    -e 's/:/\\:/g'
}

preserve_local_property() {
  local key="$1"
  local file="$2"

  if [ ! -f "$file" ]; then
    return 0
  fi

  sed -n "s/^${key}=//p" "$file" | head -n 1
}

clerk_publishable_key="$(dotenv_value CLERK_PUBLISHABLE_KEY)"
if [ -z "$clerk_publishable_key" ]; then
  clerk_publishable_key="$(dotenv_value EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY)"
fi

premium_product_ids="$(dotenv_value AVRADIO_PREMIUM_PRODUCT_IDS)"
support_email="$(dotenv_value AVRADIO_SUPPORT_EMAIL)"
account_management_url="$(dotenv_value AVRADIO_ACCOUNT_MANAGEMENT_URL)"
terms_url="$(dotenv_value AVRADIO_TERMS_URL)"
privacy_url="$(dotenv_value AVRADIO_PRIVACY_URL)"

auth_provider="${AVRADIO_AUTH_PROVIDER:-clerk}"
auth_web_url="${AVRADIO_AUTH_WEB_URL:-}"
auth_callback_scheme="${AVRADIO_AUTH_CALLBACK_SCHEME:-avradio}"
auth_callback_host="${AVRADIO_AUTH_CALLBACK_HOST:-auth}"

required_values=(
  clerk_publishable_key
  premium_product_ids
  support_email
  account_management_url
  terms_url
  privacy_url
)

for value_name in "${required_values[@]}"; do
  if [ -z "${!value_name:-}" ]; then
    echo "Missing required value: $value_name" >&2
    exit 1
  fi
done

rendered_config="$(cat <<EOF
## Generated by scripts/generate-android-local-properties.sh for profile '$profile'
AVRADIO_APPLICATION_ID=$(properties_escape "$application_id")
AVRADIO_AUTH_PROVIDER=$(properties_escape "$auth_provider")
CLERK_PUBLISHABLE_KEY=$(properties_escape "$clerk_publishable_key")
AVRADIO_AUTH_WEB_URL=$(properties_escape "$auth_web_url")
AVRADIO_AUTH_CALLBACK_SCHEME=$(properties_escape "$auth_callback_scheme")
AVRADIO_AUTH_CALLBACK_HOST=$(properties_escape "$auth_callback_host")
AVRADIO_PREMIUM_PRODUCT_IDS=$(properties_escape "$premium_product_ids")
AVRADIO_SUPPORT_EMAIL=$(properties_escape "$support_email")
AVRADIO_ACCOUNT_MANAGEMENT_URL=$(properties_escape "$account_management_url")
AVRADIO_TERMS_URL=$(properties_escape "$terms_url")
AVRADIO_PRIVACY_URL=$(properties_escape "$privacy_url")
EOF
)"

target_file="$repo_root/apps/android/local.properties"
sdk_dir="$(preserve_local_property sdk.dir "$target_file")"
ndk_dir="$(preserve_local_property ndk.dir "$target_file")"
cmake_dir="$(preserve_local_property cmake.dir "$target_file")"

if [ -n "$sdk_dir" ]; then
  rendered_config="${rendered_config}
sdk.dir=${sdk_dir}"
fi

if [ -n "$ndk_dir" ]; then
  rendered_config="${rendered_config}
ndk.dir=${ndk_dir}"
fi

if [ -n "$cmake_dir" ]; then
  rendered_config="${rendered_config}
cmake.dir=${cmake_dir}"
fi

case "$output_mode" in
  write)
    umask 077
    printf '%s\n' "$rendered_config" > "$target_file"
    echo "Wrote $target_file for profile '$profile'."
    ;;
  stdout)
    printf '%s\n' "$rendered_config"
    ;;
  *)
    echo "Unsupported output mode: $output_mode" >&2
    exit 1
    ;;
esac
